### PR TITLE
run-length-encoding-exercise: added new exercise.

### PR DESCRIPTION
**Pull request by SimaDovakin**
Added new exercise for #48in24.

### CODE REVIEW

**Comment by keiravillekode** [comment]
It would be excellent if we had a `instructions.append.md` that explains the memory addresses the student's solution is expected to use.

If I understand correctly, your example solution uses some memory near address 0 and some memory near address 320, in addition to the memory for the input string.


Should we perhaps be passing in a destination address?

**Comment by SimaDovakin** [comment]
In `instructions.append.md`, I mentioned that the buffer for the input string uses bytes 64-319 of linear memory. I use the memory from 0 as the main input memory and the memory from 320 for storing the digits of a number to convert them to a number. But, maybe, there are other solutions that don't require the memory from 320. I think, it is enough to specify the input memory range. Am I right? Maybe I missed something.

**Comment by keiravillekode** [comment]
My solutions on other low-level tracks would write the digits to the output in reverse order, and then reverse in place.

**Comment by SimaDovakin** [comment]
I also do it in `encode` function (actually in `$numberToString`). But for decode function I store digits in the memory from 320th byte and then consume them to get a single number. I did it because I need to know the number of digits to determine the power of ten for the last digits (123 = 1 * 10^2 + 2 * 10^1 + 3 * 10^0). I have no idea is there a way to do this conversion without storing digits.

**Comment by keiravillekode** [comment]
> (123 = 1 * 10^2 + 2 * 10^1 + 3 * 10^0). 

```
number = 0
for digit in digits:
  number = number * 10 + (digit - '0')
```

`0 * 10 + 1` gives `1`
`1 * 10 + 2` gives `12`
`12 * 10 + 3` gives `123`

**Comment by SimaDovakin** [comment]
Cool! Thank you. I'll try to reimplement this part of my solution.

**Comment by SimaDovakin** [comment]
@keiravillekode  Done. I changed the number consuming in decode function. Anything else?

**Comment by keiravillekode** [comment]
@ErikSchierboom - we can't see the updates until the PR is reopened.


I think we can merge this and we might want to refine or expand `instructions.append.md` afterwards. A flood of people will attempt this exercise for #48in24 and we want them to have an excellent experience.

In a month or two, we can decide on sample solutions for Dig Deeper.

Here are my two suggestions:

One solution for this exercise would overwrite the input with the output. For the `decode` case, I would compute the output length and work backwards from the end to the start, returning early as soon as outputIndex equals inputIndex - so decode "abc10d2e" would write 2 'e' characters, then the 10 'd' characters and then return.

Another solution would write the output immediately after the input in memory - assuming `instructions.append.md` can be phrased such that this is a permissible solution.  Perhaps with wording like "There is also sufficient space for the output string, both before and after the input string."    This example solution would generate the `encode` output initially reversed, and reverse in place at the very end.  So encode 'abbbbbbbbbbbbc' would write 'cb21a'  and then reverse that.

**Review by keiravillekode — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
This Now has a merge conflict

**Comment by SimaDovakin** [comment]
I'll resolve it.

**Comment by SimaDovakin** [comment]
@ErikSchierboom Done

**Pull request merged**
