### PR TITLE
Add Knapsack exercise

### PR DESCRIPTION
**Pull request by kahgoh**
This is one of the 48in24 exercises.

### CODE REVIEW

**Comment by keiravillekode** [comment]
We can add a `instructions.append.md` that mentions the items are passed in as an array of (weight, value) pairs of 32 bit unsigned numbers.  I don't have a specific phrasing suggestion.

If we do mention 'unsigned', I suspect `get_mem_as_i32` should become `get_mem_as_u32`


We could include something like

> If you so choose, you may overwrite the addresses of linear memory used for the input.

**Comment by kahgoh** [comment]
Thanks for the suggestion @keiravillekode.

I have just added something for the `instructions.append.md`. I left out `unsigned` as I thought that might be simpler (otherwise, it implies solutions should load the numbers into `i64` with `i64.load32_u`).

**Comment by keiravillekode** [comment]
@ErikSchierboom please reopen.

I've [asked](https://forum.exercism.org/t/webassembly-maintainer/11914) to be a maintainer.

**Review by keiravillekode — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
I'm away for a bit, but I'll get your maintainership setup next week

**Pull request merged**
